accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns=[
    path('register',views.user_register,name="register"),
    path('',views.user_login,name="login"),
]

index/urls.py
from django.urls import path
from . import views

app_name="index"
urlpatterns=[
    path('',views.map,name="index"),
    path('getdata',views.getdata,name='getdata'),
     path('addVectorToDb',views.addVectorToDb,name='addVectorToDb'),
     path('GetVectorFromDB',views.GetVectorFromDB,name='GetVectorFromDB'),
     path('virayeshVector',views.virayeshVector,name='virayeshVector'),
     path('delete_feature',views.delete_feature,name='delete_feature'),
     path('Identify',views.Identify,name='Identify'),
]

mygis_proj/urls.py
from django.contrib import admin
from django.urls import path,include
#import baraye static file vaimage
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('accounts', include('accounts.urls')),
    path('accounts', include('django.contrib.auth.urls')),
]

#sttaticroot darimmmmmmmmmmmmmmmmmmmmmm
urlpatterns +=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

index/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

class SiteUser(models.Model):
    is_staff = models.BooleanField(default=False,verbose_name='کارمند')
    is_active = models.BooleanField(default=True,verbose_name='فعال')
    name = models.CharField(_("نام کاربری"), max_length=100,unique=True, help_text='منحصر به فرد')
    email = models.EmailField(_("آدرس الکترونیکی"), max_length=254,unique=True)
    class Meta:
        managed = True
        db_table = 'siteuser'
    def __str__(self):
        return self.name   

class LayerModel(models.Model):
   
    en_name = models.CharField(max_length=50)
    fa_name = models.CharField(max_length=50)
    url = models.CharField(max_length=100)

    class Meta:
        managed = True
        db_table = 'layers'
    def __str__(self):
        return self.fa_name   

class UserVector(models.Model):
    
    
    wkt=models.CharField(max_length=1000)
    geojson=models.CharField(max_length=1000)
    user_d=models.IntegerField(blank=True, null=True)
    owner=models.CharField(max_length=1000,blank=True, null=True)
    code=models.IntegerField(blank=True, null=True)

    class Meta:
        managed =True
        db_table = 'uservectors'
   

accounts/forms.py
from django import forms

class UserRegistrationForm(forms.Form):
    username=forms.CharField()
    email=forms.EmailField()
    password=forms.CharField()

class UserLoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField()

index/forms.py
from django import forms
# from .models import UserVector

# class UservectorForm(forms.ModelForm):
#     class Meta:
#         model =UserVector
#         fields = ["owner","code"]

class UservectorForm(forms.Form):
   
    owner = forms.CharField(max_length=100)
    code = forms.IntegerField()

accounts/views.py
from django.shortcuts import render ,redirect
from .forms import UserRegistrationForm,UserLoginForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate ,login,logout
from django.contrib import messages
# Create your views here.

def user_register(request):
    if request.method=='POST':
        form=UserRegistrationForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            User.objects.create_user(cd['username'],cd['email'],cd['password'])
            messages.success(request,'bamova','success')
            return redirect ("accounts:login")

    else:
        form=UserRegistrationForm()
        messages.success(request,'jfghgka','success')
    return render(request,'accounts/register.html',{'form':form})


def user_login(request):
    if request.method=='POST':
        form=UserLoginForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            user= authenticate(request,username=cd['username'],password=cd['password'])
            if user is not None:
                login(request,user)
                messages.success(request,'gggggggggggg','success')
                return redirect ("index:index")
            else:
                 messages.error(request,'rrrrrrr','danger')
        else:  
            return render(request,'accounts/login.html',{'form':form})       
    else:
        form=UserLoginForm()             

    return render(request,'accounts/login.html',{'form':form})

index/views.py
import requests
from django.shortcuts import render
from .models import LayerModel,UserVector
import json
from django.http import HttpResponseBadRequest, JsonResponse

from django.core.serializers import serialize
from django.core.serializers.json import DjangoJSONEncoder
from django.views.decorators.csrf import ensure_csrf_cookie
from .forms import UservectorForm

# Create your views here.
def map(request):
    layer=LayerModel.objects.all()
    laye=serialize('json',layer)
    context = {'data': json.dumps (laye)}

    # context={
    #     "laye":laye
    # }
    return render(request,"index.html",context)

def getdata(request):
     layer=LayerModel.objects.all()
     laye=serialize('json',layer)
     
    
     return JsonResponse({'data': json.dumps (laye)})

def addVectorToDb(request):
      form=UservectorForm()
      
     #  context = {
     #       "form":form,
     #      }
      if request.method == "POST":
           gg=json.loads(request.body)
           user_id1=request.user.id
           wkt1=gg
           geometry=gg
           new_serVector=UserVector(user_d=user_id1,wkt=wkt1,geojson=geometry)
           new_serVector.save()
           return JsonResponse({'success':True})
      else:
          
           return render(request,"index.html",{"form": form})
      

     
def GetVectorFromDB(request):
      vectors=UserVector.objects.filter(user_d=request.user.id).values()
#     json_data= json.dumps(list(vectors.values()),cls=DjangoJSONEncoder)
#     response=HttpResponse(json_data,content_type='application/json')
#     return  response
      data_list=list(vectors)
     #  print(data_list)
      return JsonResponse(data_list,safe=False)




# def jsonreqmap(request):
#         layer=LayerModel.objects.all()
#         json_data=serialize('json',layer)
#         python_data=json.loads(json_data)
#         # modified_json_data=json.dump(python_data)
#      return render(request,"index.html",context)

def virayeshVector(request):
     if request.method == "POST":
          d1=json.loads(request.body)
          d11=d1['f_id']
          # vector=UserVector.objects.filter(id=41)
          
          wkt11=d1['geojson22']
          UserVector.objects.filter(id=d11).update(wkt=wkt11,geojson=wkt11)
          return JsonResponse({'success':True})
     else:
           return render(request,"index.html")

def delete_feature(request):
     if request.method == "POST":
          d2=json.loads(request.body)
          # d12=d2['f_id']
          # print(d2)
          # vector=UserVector.objects.filter(id=d11)
          UserVector.objects.filter(id=d2).delete()
          return JsonResponse({'success':True})
     else:
           return render(request,"index.html")
     
def Identify(request):
       url = request.body
     #   response1=requests.get(url)
     #   print(response1)
       r={"k":"l"}
       return JsonResponse(r,safe=False)


     #  vectors=UserVector.objects.filter(user_d=request.user.id).values()
#     json_data= json.dumps(list(vectors.values()),cls=DjangoJSONEncoder)
#     response=HttpResponse(json_data,content_type='application/json')
#     return  response
      
     #  print(url)
     #  return JsonResponse(k,safe=False)

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>ورود کاربران</title>
 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form action="" method="post">
        {%csrf_token%}
        <h3>ورود به سامانه</h3>

        <label for="username">نام کاربری</label>
        <input type="text"  name="username">

        <label for="password">گذر واژه</label>
        <input type="password" name="password">

        <button>ورود</button>
        <div class="social">
          <!-- <div class="go"><i class="fab fa-google"></i>  ثبت نام</div> -->
         <a href="{% url 'accounts:register'%}"><div class="fb"></i> ثبت نام</div></a>
        </div>
    </form>
    {% if form.errors %}
       ffhjj
      <br>
      {%for field in form %}
        {% if field.errors %}
         {%for error in field.errors %}
          {{field.lable}}:{{error}}
         {%endfor%}
        {%endif%}
      {%endfor%}
      {%if form.non_field_errors%}
       {{form.non_field_errors}}
      {%endif%}
    {%endif%}
       
  
</body>
</html>

index/templates/index.html
{% extends 'base.html' %}
{%load static%}
{%block content%}


{% endblock content%}

templates/base.html
{%load static%}
<!doctype html>
<html lang="en">
  <head>
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/ol@v9.1.0/ol.css">
    <!-- <link rel="stylesheet" href="{% static 'css/ol.css' %}"> -->
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.css' %}">
    <link href="{% static 'css/jstree/default/style.css' %}" rel="stylesheet" />

    <link rel="stylesheet" href="{% static 'css/jquery.modal.min.css' %}">
    <style>
      .map {
        height: 400px;
        width: 100%;
      }
      .ol-popup {
        
        background-color: white;
        box-shadow: 0 1px 4px rgba(0,0,0,0.2);
        padding: 15px;
        border-radius: 10px;
        border: 1px solid #cccccc;
        bottom: 12px;
        left: -50px;
        min-width: 280px;
      }
      .ol-popup:after, .ol-popup:before {
        top: 100%;
        border: solid transparent;
        content: " ";
        height: 0;
        width: 0;
        position: absolute;
        pointer-events: none;
      }
      .ol-popup:after {
        border-top-color: white;
        border-width: 10px;
        left: 48px;
        margin-left: -10px;
      }
      .ol-popup:before {
        border-top-color: #cccccc;
        border-width: 11px;
        left: 48px;
        margin-left: -11px;
      }
      .ol-popup-closer {
        text-decoration: none;
        position: absolute;
        top: 2px;
        right: 8px;
      }
      .ol-popup-closer:after {
        content: "✖";
      }
      .jstree li {
        float: none;
        height: auto;
    }

    .jstree-hovered, .jstree-wholerow-hovered {
        background-color: #21c09f !important;
    }

    .jstree-icon.jstree-themeicon {
        display: none;
    }
    .collapsible {
  background-color: #a2bfda;
  color: #444;
  cursor: pointer;
  padding: 18px;
  position: absolute;
  width:120px;
  border: none;
  text-align: left;
  outline: none;
  font-size: 15px;
  z-index: 1000;
 right: 20px;
}

/* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
.active, .collapsible:hover {
  background-color: #8a8cd5;
}

/* Style the collapsible content. Note: hidden by default */
.content {
  padding: 0 18px;
  display: none;
  overflow: hidden;
  background-color: #f1f1f1;
}
    </style>
    
    <title>سامانه اطلاعات مکانی</title>
  </head>
  <body>
    <div class="icon-bar" >
      <a  href="{% url 'accounts:login'%}"><i class="fa fa-sign-in" style="font-size:24px"></i></a>
      <a  href="{% url 'logout'%}"><i class="fa fa-sign-out" style="font-size:24px" ></i></a>
      <a href="#"><i class="fa "><img  src="{% static 'img/zoom-extent.png' %}" onclick="zoom_ex()" title="zoom extent" id="zx" ></i></a>
      <!-- <a href="#"  id="aatt" class="jjj" >cccc</a> -->

      {%if user.is_authenticated %}
      <a href="#" class="toolb LineString" ><i class="fa "></i><img  src="{% static 'img/line-create.png' %}" onclick="draw_control('LineString')" title="draw line"></a>
      <a href="#" class="toolb Point" ><i class="fa "></i><img  src="{% static 'img/point-create.png' %}" onclick="draw_control('Point')" title="draw point"></a>
      <a href="#" class="toolb Polygon"><i class="fa "></i><img  src="{% static 'img/polygon-create.png' %}" onclick="draw_control('Polygon')" title="draw polygon"></a>
      <a href="#" class="edit"><i class="fa "></i><img  src="{% static 'img/edit.png' %}" onclick="modif()" title="ویرایش عوارض" ></a>
      <a href="#" class="del"><i class="fa "></i><img  src="{% static 'img/selected-delete.png' %}" onclick="delete1()" title="حذف عارضه"></a>
      <a href="#" class="del"><i class="fa "></i><img  src="{% static 'img/id.png' %}" onclick="iden()" title="اطلاعات توصی"></a>
      
      {% endif %}
    
    </div>
    
    <button type="button" class="collapsible">لایه های نقشه</button>
   
  <!-- layerrrrrr -->
  <div id="layers" class="content" style="width:250px;direction: rtl;height:auto;background-color:#a3a9aa;position:absolute;right:0px;top:50px;z-index:2000">
    
    <div style="height:50px"></div>
    <!-- 3 setup a container element position:absolute;right:0px;top:150px;z-index:2000 -->
    <div id="legend_layers">
        
    </div>
    <!-- <div style="width:100%;text-align:center;margin-top:30px">
        <button id="btn_set_access_level" style="font-family:Tahoma; background-color:#27a087;width:200px;height:40px;border:0px;color:#fff;cursor:pointer" onclick="set_access_level()">اعمال دسترسی به لایه ها</button>
    </div> -->
</div>
    
    <div id="map" class="map" style="height:700px;">
      <!-- <div id="zooms" class='zoom_slider111' style="width:150px;height:40px;position:absolute;left:10px;bottom:30px;z-index:2000;background:#434a5a;color:#fff;opacity: 0.6;text-align:left;padding:10px;border:1px solid #d0d0d0"></div></div> -->

      <div id="location" class='custom-mouse-position' style="width:150px;height:40px;position:fixed;left:10px;bottom:30px;z-index:2000;background:#434a5a;color:#fff;opacity: 0.6;text-align:left;padding:10px;border:1px solid #d0d0d0"></div>
    <!-- <div style="display: none" id="jsonData" data-json="{{ data }}"></div> -->
    
    <div id="popup" class="ol-popup">
      <a href="#" id="popup-closer" class="ol-popup-closer"></a>
      <div id="popup-content">   
        <div><h1>{{request.user.id}}</h1></div>
      </div>
    </div>
  
   <div id="attable" class="attable" dir="rtl" style="display: none;">
      <form method="POST" >
        {% csrf_token %}
        <div class="div">malek</div>
        <input id="owner" name="owner">
        <div class="div">cod</div>
        <input id="code" name="code">
        <div class="div">
          <button  id="submit" type="submit">OK</button>
        </div>
        
      </form>
   </div>
    
   
    {%block content%}

 
    {%endblock content%}
   

    <script src="https://cdn.jsdelivr.net/npm/ol@v9.1.0/dist/ol.js"></script>
    <!-- <script src="{% static 'js/jstree.js' %}"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/1.12.1/jquery.min.js"></script>
    <!-- <script src="{% static 'js/jquery.modal.min.js' %}"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.2/jquery.modal.min.js"></script>
    <script src="{% static 'js/jstree.js' %}"></script>
    <script src="{% static 'js/jstree.min.js' %}"></script>
    <script src="{% static 'js/jstree.checkbox.js' %}"></script>
    <script src="{% static 'js/jstree.wholerow.js' %}"></script>
   
    
    <!-- <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script> -->
    <!-- <script src="{% static 'js/ol.js' %}"></script> -->
    <script src="{% static 'js/ol-layerswitcher.js' %}"></script>
    <script src="{% static 'js/map.js' %}"></script> 
    <script>
      /////دکمه لایه ها
var coll = document.getElementsByClassName("collapsible");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.display === "block") {
      content.style.display = "none";
    } else {
      content.style.display = "block";
    }
  });
}

////فرم ایجاد اطلاعات توصیفی

// $('#aatt').click(function () {

// $("#attable").modal();
// });

       var layer_json = [];
    var data = JSON.parse ("{{data | escapejs}}");
    
    var d=(new Function("return [" + data+ "];")());
   
    var lala=d[0][0]['fields']
    
    for (let i = 0; i < d[0].length; i++) {
     //console.log(d[0][i]['fields'].en_name)
      var url1=d[0][i]['fields'].url;
      var en_name1=d[0][i]['fields'].en_name;
      var id1=d[0][i]['fields'].id;
      var fa_name1=d[0][i]['fields'].fa_name;
      var source = new ol.source.TileWMS({
            url: url1,
            params: { 'LAYERS': en_name1, 'TILED': true },
            serverType: 'geoserver',

        });
        map.addLayer(new ol.layer.Tile({
            source: source,
            opacity: 0.6,
            title:  en_name1
        }));
        layer_json.push({ 'id': en_name1 + '$' + id1, 'text': fa_name1,'title': en_name1 });

    }

</script>
<script>
    $(document).ready(function () {
      get_user_vector();
      create_legend();
    });
   function add_vector_to_db(geojson1) {
        let csrftoken = '{{ csrf_token }}'
        //data_for_send = { "geometry": geojson1 };
        data_for_send = geojson1;
        $.ajax({
          
            url:  '{%url 'index:addVectorToDb'  %}',
            type: 'POST',
            headers:{'X-CSRFToken':csrftoken},
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify(data_for_send),
          
            success: function () {
              // console.log(typeof(geojson1))
            },
            fail: function () {
              
            }
        });
    };

    function get_user_vector() {
        $.ajax({

            type: 'GET',
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            url: '{%url 'index:GetVectorFromDB'  %}',
            success: 
            function (response) {            
             format = new ol.format.GeoJSON();
              //var d=JSON.parse(JSON.stringify(response) )
              //ff=JSON.loads(d[0].geojson)
              //console.log(response)
              for (i = 0; i < response.length; i++) {
                   //lkhg=JSON.loads(response[0].geojson)
                  // console.log(typeof(lkhg))
                   //var features = format.readFeatures(d[i].geojson);
                  //ff= JSON.parse(JSON.stringify(d[i].geojson))
                  b=response[i].geojson
                 // console.log(b)
                   deserialize(b,response[i].id);
                    
                }
                
              }
            ,
            fail: function (data) {

            }
        });
    }

    function modif_selected(f_id,geojson22) {
      let csrftoken = '{{ csrf_token }}'
        data_for_send = { "f_id": f_id, "geojson22": geojson22}
        $.ajax({
            url:  '{%url 'index:virayeshVector'  %}',
            type: 'POST',
            headers:{'X-CSRFToken':csrftoken},
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify(data_for_send),
          
            success: function () {
              //console.log(data_for_send)
            },
            fail: function () {
              
            }
        });
    };
    function delete_selected(f_id) {
    
      let csrftoken = '{{ csrf_token }}'
       
        data_for_send = f_id;
        $.ajax({
          
            url:  '{%url 'index:delete_feature'  %}',
            type: 'POST',
            headers:{'X-CSRFToken':csrftoken},
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            data: JSON.stringify(data_for_send),
          
            success: function () {
              //console.log(data_for_send)
            },
            fail: function () {
              
            }
        });

    }
    function iden(){
      $.ajax({

        type: 'GET',
        dataType: 'json',
        contentType: 'application/json; charset=utf-8',
        url: '{%url 'index:Identify'  %}',
        success: function (response) {  
                identify();          
                // format = new ol.format.GeoJSON();
               
                // for (i = 0; i < response.length; i++) {
           
                //   b=response[i].geojson
                //   // console.log(b)
                 
                //  }
                },
        fail: function (data) {}
    })}
  
</script>

<script>
  var identify_url = '{%url 'index:Identify'  %}';
</script>
  </body>
   
  
</html>

 <!-- user_id=  models.ForeignKey(User, verbose_name=_("کاربر"), related_name="uservector" , on_delete=models.CASCADE,blank=True, null=True)  -->

templates/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <!-- <title> Sign up / Login Form</title> -->
  <link rel="stylesheet" href="{% static 'css/loginstyle.css' %}">

</head>
<body>
<!-- partial:index.partial.html -->

	<div class="main">  	
		<input type="checkbox" id="chk" aria-hidden="true">

			<div class="signup">
				<form>
					<label for="chk" aria-hidden="true">Sign up</label>
					<input type="text" name="txt" placeholder="User name" required="">
					<input type="email" name="email" placeholder="Email" required="">
					<input type="password" name="pswd" placeholder="Password" required="">
					<button>Sign up</button>
				</form>
			</div>

			<div class="login">
				<form>
					<label for="chk" aria-hidden="true">Login</label>
					<input type="email" name="email" placeholder="Email" required="">
					<input type="password" name="pswd" placeholder="Password" required="">
					<button>Login</button>
				</form>
			</div>
	</div>
</body>
</html>
partial








/////////////////////////

<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Design by foolishdeveloper.com -->
    <title>ورود کاربران</title>
 
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;500;600&display=swap" rel="stylesheet">
    <!--Stylesheet-->
    <style media="screen">
      *,
*:before,
*:after{
    padding: 0;
    margin: 0;
    box-sizing: border-box;
}
body{
    background-color: #080710;
}
.background{
    width: 430px;
    height: 520px;
    position: absolute;
    transform: translate(-50%,-50%);
    left: 50%;
    top: 50%;
}
.background .shape{
    height: 200px;
    width: 200px;
    position: absolute;
    border-radius: 50%;
}
.shape:first-child{
    background: linear-gradient(
        #1845ad,
        #23a2f6
    );
    left: -80px;
    top: -80px;
}
.shape:last-child{
    background: linear-gradient(
        to right,
        #ff512f,
        #f09819
    );
    right: -30px;
    bottom: -80px;
}
form{
    height: 520px;
    width: 400px;
    background-color: rgba(255,255,255,0.13);
    position: absolute;
    transform: translate(-50%,-50%);
    top: 50%;
    left: 50%;
    border-radius: 10px;
    backdrop-filter: blur(10px);
    border: 2px solid rgba(255,255,255,0.1);
    box-shadow: 0 0 40px rgba(8,7,16,0.6);
    padding: 50px 35px;
}
form *{
    font-family: 'Poppins',sans-serif;
    color: #ffffff;
    letter-spacing: 0.5px;
    outline: none;
    border: none;
}
form h3{
    font-size: 32px;
    font-weight: 500;
    line-height: 42px;
    text-align: center;
}

label{
    display: block;
    margin-top: 30px;
    font-size: 16px;
    font-weight: 500;
}
input{
    display: block;
    height: 50px;
    width: 100%;
    background-color: rgba(255,255,255,0.07);
    border-radius: 3px;
    padding: 0 10px;
    margin-top: 8px;
    font-size: 14px;
    font-weight: 300;
}
::placeholder{
    color: #e5e5e5;
}
button{
    margin-top: 50px;
    width: 100%;
    background-color: #ffffff;
    color: #080710;
    padding: 15px 0;
    font-size: 18px;
    font-weight: 600;
    border-radius: 5px;
    cursor: pointer;
}
.social{
  margin-top: 30px;
  display: flex;
}
.social div{
  background: red;
  width: 150px;
  border-radius: 3px;
  padding: 5px 10px 10px 5px;
  background-color: rgba(255,255,255,0.27);
  color: #eaf0fb;
  text-align: center;
}
.social div:hover{
  background-color: rgba(255,255,255,0.47);
}
.social .fb{
  margin-left: 25px;
}
.social i{
  margin-right: 4px;
}

    </style>
</head>
<body>
    <div class="background">
        <div class="shape"></div>
        <div class="shape"></div>
    </div>
    <form action="" method="post">
        {%csrf_token%}
        <h3>ورود به سامانه</h3>

        <label for="username">نام کاربری</label>
        <input type="text"  name="username">

        <label for="password">گذر واژه</label>
        <input type="password" name="password">

        <button>ورود</button>
        <div class="social">
          <!-- <div class="go"><i class="fab fa-google"></i>  ثبت نام</div> -->
         <a href="{% url 'accounts:register'%}"><div class="fb"></i> ثبت نام</div></a>
        </div>
    </form>
    {% if form.errors %}
       ffhjj
      <br>
      {%for field in form %}
        {% if field.errors %}
         {%for error in field.errors %}
          {{field.lable}}:{{error}}
         {%endfor%}
        {%endif%}
      {%endfor%}
      {%if form.non_field_errors%}
       {{form.non_field_errors}}
      {%endif%}
    {%endif%}
       
  
</body>
</html>